services:

  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "3306:3306"

    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10


  app:
    build: .

    container_name: ecommerce-etl

    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    depends_on:
      mysql:
        condition: service_healthy


  airflow-postgres:
    image: postgres:16

    container_name: ecommerce-airflow-postgres

    environment:
      POSTGRES_USER: ${AIRFLOW_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_POSTGRES_DB}

    volumes:
      - airflow-postgres-data:/var/lib/postgresql/data


  airflow-api:
    build:
      context: .
      dockerfile: airflow/Dockerfile

    container_name: ecommerce-airflow-api

    command: api-server --port 8080

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${AIRFLOW_POSTGRES_USER}:${AIRFLOW_POSTGRES_PASSWORD}@airflow-postgres:5432/${AIRFLOW_POSTGRES_DB}"
      AIRFLOW__CORE__AUTH_MANAGER: "airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager"

      AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW_JWT_SECRET}

      PYTHONPATH: /opt/airflow

      MYSQL_HOST: mysql
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./python:/opt/airflow/python
      - ./data:/opt/airflow/data

    ports:
      - "8080:8080"

    depends_on:
      mysql:
        condition: service_healthy

      airflow-postgres:
        condition: service_started


  airflow-scheduler:
    build:
      context: .
      dockerfile: airflow/Dockerfile

    container_name: ecommerce-airflow-scheduler

    command: scheduler

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${AIRFLOW_POSTGRES_USER}:${AIRFLOW_POSTGRES_PASSWORD}@airflow-postgres:5432/${AIRFLOW_POSTGRES_DB}"
      AIRFLOW__CORE__AUTH_MANAGER: "airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager"
      AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW_JWT_SECRET}
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-api:8080/execution/"

      PYTHONPATH: /opt/airflow

      MYSQL_HOST: mysql
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./python:/opt/airflow/python
      - ./data:/opt/airflow/data

    depends_on:
      mysql:
        condition: service_healthy

      airflow-postgres:
        condition: service_started


  airflow-dag-processor:
    build:
      context: .
      dockerfile: airflow/Dockerfile

    container_name: ecommerce-airflow-dag-processor

    command: dag-processor

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${AIRFLOW_POSTGRES_USER}:${AIRFLOW_POSTGRES_PASSWORD}@airflow-postgres:5432/${AIRFLOW_POSTGRES_DB}"

      AIRFLOW__CORE__AUTH_MANAGER: "airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager"

      PYTHONPATH: /opt/airflow

      MYSQL_HOST: mysql
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./python:/opt/airflow/python
      - ./data:/opt/airflow/data

    depends_on:
      airflow-postgres:
        condition: service_started


volumes:
  airflow-postgres-data: